baseURL = 'https://singhster-05.github.io/jugaad/'
languageCode = 'en-us'
title = 'jugaad'
theme = 'PaperMod'

[params]
defaultTheme = 'auto'
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Aditya Singh"
subtitle = "AI, MLE & Software"

[menu]
main = [
    { identifier = 'home', name = 'Home', url = '/', weight = 10 },
    { identifier = 'about', name = 'About', url = '/about/', weight = 20 },
    { identifier = 'blog', name = 'Blog', url = '/blog/', weight = 30 },
    { identifier = 'projects', name = 'Projects', url = '/projects/', weight = 40 }
]
